twig:
    default_path: '%kernel.project_dir%/templates'
<<<<<<< ours
    # form_themes: ['bootstrap_4_layout.html.twig']
    form_themes: ['front/register/form_theme.html.twig']
                    
=======

when@test:
    twig:
        strict_variables: true
>>>>>>> theirs
