<?php

declare(strict_types=1);

namespace PackageVersions;

use Composer\InstalledVersions;
use OutOfBoundsException;

class_exists(InstalledVersions::class);

/**
 * This class is generated by composer/package-versions-deprecated, specifically by
 * @see \PackageVersions\Installer
 *
 * This file is overwritten at every run of `composer install` or `composer update`.
 *
 * @deprecated in favor of the Composer\InstalledVersions class provided by Composer 2. Require composer-runtime-api:^2 to ensure it is present.
 */
final class Versions
{
    /**
     * @deprecated please use {@see self::rootPackageName()} instead.
     *             This constant will be removed in version 2.0.0.
     */
    const ROOT_PACKAGE_NAME = '__root__';

    /**
     * Array of all available composer packages.
     * Dont read this array from your calling code, but use the \PackageVersions\Versions::getVersion() method instead.
     *
     * @var array<string, string>
     * @internal
     */
    const VERSIONS          = array (
  'behat/transliterator' => 'v1.5.0@baac5873bac3749887d28ab68e2f74db3a4408af',
  'composer/package-versions-deprecated' => '1.11.99.1@7413f0b55a051e89485c5cb9f765fe24bb02a7b6',
  'doctrine/annotations' => '1.14.3@fb0d71a7393298a7b232cbf4c8b1f73f3ec3d5af',
  'doctrine/cache' => '2.2.0@1ca8f21980e770095a31456042471a57bc4c68fb',
  'doctrine/collections' => '1.8.0@2b44dd4cbca8b5744327de78bafef5945c7e7b5e',
  'doctrine/common' => '3.4.3@8b5e5650391f851ed58910b3e3d48a71062eeced',
  'doctrine/dbal' => '3.8.0@d244f2e6e6bf32bff5174e6729b57214923ecec9',
  'doctrine/deprecations' => '1.1.2@4f2d4f2836e7ec4e7a8625e75c6aa916004db931',
  'doctrine/doctrine-bundle' => '2.7.0@d2088fc50494e4e7441fecca54732245a613eeb6',
  'doctrine/doctrine-migrations-bundle' => '3.2.5@90be4395597432a05ae9aad5e6fe490622226a77',
  'doctrine/event-manager' => '1.2.0@95aa4cb529f1e96576f3fda9f5705ada4056a520',
  'doctrine/inflector' => '2.0.9@2930cd5ef353871c821d5c43ed030d39ac8cfe65',
  'doctrine/instantiator' => '1.5.0@0a0fa9780f5d4e507415a065172d26a98d02047b',
  'doctrine/lexer' => '2.1.0@39ab8fcf5a51ce4b85ca97c7a7d033eb12831124',
  'doctrine/migrations' => '3.4.3@362f07ff732a2b4498be919561536800cec29500',
  'doctrine/orm' => '2.17.3@398ab0547aaf90bdb352b560a94c24f44ff00670',
  'doctrine/persistence' => '2.5.7@e36f22765f4d10a7748228babbf73da5edfeed3c',
  'doctrine/sql-formatter' => '1.1.3@25a06c7bf4c6b8218f47928654252863ffc890a5',
  'dompdf/dompdf' => 'v1.2.2@5031045d9640b38cfc14aac9667470df09c9e090',
  'egulias/email-validator' => '3.2.6@e5997fa97e8790cdae03a9cbd5e78e45e3c7bda7',
  'friendsofphp/proxy-manager-lts' => 'v1.0.16@ecadbdc9052e4ad08c60c8a02268712e50427f7c',
  'gedmo/doctrine-extensions' => 'v3.4.0@85d58c24584a50db3872357ab6a68e3479ae7590',
  'laminas/laminas-code' => '4.7.1@91aabc066d5620428120800c0eafc0411e441a62',
  'monolog/monolog' => '2.9.2@437cb3628f4cf6042cc10ae97fc2b8472e48ca1f',
  'phenx/php-font-lib' => '0.5.5@671df0f3516252011aa94f9e8e3b3b66199339f8',
  'phenx/php-svg-lib' => '0.4.1@4498b5df7b08e8469f0f8279651ea5de9626ed02',
  'phpdocumentor/reflection-common' => '2.2.0@1d01c49d4ed62f25aa84a747ad35d5a16924662b',
  'phpdocumentor/reflection-docblock' => '5.3.0@622548b623e81ca6d78b721c5e029f4ce664f170',
  'phpdocumentor/type-resolver' => '1.8.0@fad452781b3d774e3337b0c0b245dd8e5a4455fc',
  'phpstan/phpdoc-parser' => '1.25.0@bd84b629c8de41aa2ae82c067c955e06f1b00240',
  'psr/cache' => '1.0.1@d11b50ad223250cf17b86e38383413f5a6764bf8',
  'psr/container' => '1.1.2@513e0666f7216c7459170d56df27dfcefe1689ea',
  'psr/event-dispatcher' => '1.0.0@dbefd12671e8a14ec7f180cab83036ed26714bb0',
  'psr/link' => '1.0.0@eea8e8662d5cd3ae4517c9b864493f59fca95562',
  'psr/log' => '1.1.4@d49695b909c3b7628b6289db5479a1c204601f11',
  'sabberworm/php-css-parser' => '8.4.0@e41d2140031d533348b2192a83f02d8dd8a71d30',
  'sensio/framework-extra-bundle' => 'v5.6.1@430d14c01836b77c28092883d195a43ce413ee32',
  'stof/doctrine-extensions-bundle' => 'v1.7.2@5cfabc774ee0df1904b10cd03ceb39d993bb61bd',
  'symfony/apache-pack' => 'v1.0.1@3aa5818d73ad2551281fc58a75afd9ca82622e6c',
  'symfony/asset' => 'v5.2.12@abe64fee9fa2978c730c84d0d6df760f2d9ddba0',
  'symfony/cache' => 'v5.2.12@b59303192fb99c8b3d3abc0b5975c7512fe6d1f4',
  'symfony/cache-contracts' => 'v2.5.2@64be4a7acb83b6f2bf6de9a02cee6dad41277ebc',
  'symfony/config' => 'v5.2.12@32f6be0d0c2e204ff35759f9ee81d4f5e83b7acb',
  'symfony/console' => 'v5.2.14@ffc2722adb0983451855c794c4bc7818d3c65fa2',
  'symfony/dependency-injection' => 'v5.2.12@2f0326ab0e142a3600b1b435cb3e852bc96264b6',
  'symfony/deprecation-contracts' => 'v2.5.2@e8b495ea28c1d97b5e0c121748d6f9b53d075c66',
  'symfony/doctrine-bridge' => 'v5.2.12@0212d2d1e17a3e7403475b76e26fc1f0f1add04b',
  'symfony/dotenv' => 'v5.2.14@12888c9c46ac750ec5c1381db5bf3d534e7d70cb',
  'symfony/error-handler' => 'v5.2.12@7ca5fa510345f6b8def43b18c900852defaee362',
  'symfony/event-dispatcher' => 'v5.2.12@6a32cd803f8ff33d84b709de3978f44a62e42961',
  'symfony/event-dispatcher-contracts' => 'v2.5.2@f98b54df6ad059855739db6fcbc2d36995283fe1',
  'symfony/expression-language' => 'v5.2.12@d4367d36217dd395b10f61649a6bf2c1367140d8',
  'symfony/filesystem' => 'v5.2.12@ed397ef25365b3db9f215af4ed5b1ec8a5b10989',
  'symfony/finder' => 'v5.2.12@17f50e06018baec41551a71a15731287dbaab186',
  'symfony/flex' => 'v1.21.4@7b40eec950ded5de7054f807c209d3c612efe517',
  'symfony/form' => 'v5.2.12@929811a7667aa5814f93a70974423870b14c05aa',
  'symfony/framework-bundle' => 'v5.2.12@4e9ca1c60dba3b5e261eadd3b427bc115914b72b',
  'symfony/http-client' => 'v5.2.12@1895ede860a198803395a67738104211508b5ddc',
  'symfony/http-client-contracts' => 'v2.5.2@ba6a9f0e8f3edd190520ee3b9a958596b6ca2e70',
  'symfony/http-foundation' => 'v5.2.14@2a247de56fc8f5efdf1e098192128e8e509d370c',
  'symfony/http-kernel' => 'v5.2.14@2c3b9af1047c477c527504a3509ab59e4fae0689',
  'symfony/intl' => 'v5.2.12@23ae12a613eb77725c6ef6a15d37b0e9956c6a2a',
  'symfony/mailer' => 'v5.2.12@75ea7f9e54c1bc49b6d7e3d6b20422f85b7ea3e4',
  'symfony/mime' => 'v5.2.12@6ad63acd694b30e75fb2426b037e92859df73d6b',
  'symfony/monolog-bridge' => 'v5.2.12@2c3943d7c0100983f9c0a82807555273353e3539',
  'symfony/monolog-bundle' => 'v3.8.0@a41bbcdc1105603b6d73a7d9a43a3788f8e0fb7d',
  'symfony/notifier' => 'v5.2.12@08f557f018e080ea36d51b43a6552bf5396e9c83',
  'symfony/options-resolver' => 'v5.2.12@1935d2e5329aba28cbb9ef6cc5687d007619d96d',
  'symfony/polyfill-intl-grapheme' => 'v1.28.0@875e90aeea2777b6f135677f618529449334a612',
  'symfony/polyfill-intl-icu' => 'v1.28.0@e46b4da57951a16053cd751f63f4a24292788157',
  'symfony/polyfill-intl-idn' => 'v1.28.0@ecaafce9f77234a6a449d29e49267ba10499116d',
  'symfony/polyfill-intl-normalizer' => 'v1.28.0@8c4ad05dd0120b6a53c1ca374dca2ad0a1c4ed92',
  'symfony/polyfill-mbstring' => 'v1.28.0@42292d99c55abe617799667f454222c54c60e229',
  'symfony/polyfill-php73' => 'v1.28.0@fe2f306d1d9d346a7fee353d0d5012e401e984b5',
  'symfony/polyfill-php80' => 'v1.28.0@6caa57379c4aec19c0a12a38b59b26487dcfe4b5',
  'symfony/polyfill-php81' => 'v1.28.0@7581cd600fa9fd681b797d00b02f068e2f13263b',
  'symfony/process' => 'v5.2.12@d16634ee55b895bd85ec714dadc58e4428ecf030',
  'symfony/property-access' => 'v5.2.12@82c6db3e4066ebc1993c377ae71090d0c8f0552c',
  'symfony/property-info' => 'v5.2.12@f9dd1886f47db8ea494d97a4b8bfa494094f53f1',
  'symfony/proxy-manager-bridge' => 'v5.2.12@76e61f33f6a34a340bf6e02211214f466e8e1dba',
  'symfony/routing' => 'v5.2.12@983a19067308962592755f57d97ca1d1f1edd37b',
  'symfony/security-bundle' => 'v5.2.12@bc36546f36355d7c0b56b23c44786b36904f838d',
  'symfony/security-core' => 'v5.2.14@4ce2b1e532fb3bb591ad4efa8cc43afc9242a247',
  'symfony/security-csrf' => 'v5.2.12@f0af6689451582e55f6b3439362e72e536e916e4',
  'symfony/security-guard' => 'v5.2.12@9edddb0b4c97eb923ba9910050be80f539933c3b',
  'symfony/security-http' => 'v5.2.12@8d6fb4fb1bb0d4a11b30de85cbf77914c71175bc',
  'symfony/serializer' => 'v5.2.12@3c3afcc285c01c486d1c5504e7895026580495c4',
  'symfony/service-contracts' => 'v2.5.2@4b426aac47d6427cc1a1d0f7e2ac724627f5966c',
  'symfony/stopwatch' => 'v5.2.12@24744393b122b8309bbcc7965972ae51a29a602d',
  'symfony/string' => 'v5.2.11@ab6dc1c796bbceffbaf9ccbfb7a24feb641d6ee7',
  'symfony/templating' => 'v5.2.12@3f4bb5c819c0418093d4d401ef82a145deb4908e',
  'symfony/translation' => 'v5.2.12@7b4ef368b25bbb758a7bd5fe20349433e84220ed',
  'symfony/translation-contracts' => 'v2.5.2@136b19dd05cdf0709db6537d058bcab6dd6e2dbe',
  'symfony/twig-bridge' => 'v5.2.12@243a7c6416fea3b91391f09831d8d04b2e42c0b1',
  'symfony/twig-bundle' => 'v5.2.12@6f2aa369c4b7da19b3c864c48e35b26451c92e4e',
  'symfony/validator' => 'v5.2.14@a46ac85624ad3418d455bb8f4ce452014c28518c',
  'symfony/var-dumper' => 'v5.2.12@d5f42c357a6672d4e5960bba85e437850e9a7abb',
  'symfony/var-exporter' => 'v5.4.32@fdb022f0d3d41df240c18e2eb9a117c430f06add',
  'symfony/web-link' => 'v5.2.12@3d1f4a0318314c63c363f5d49de15d54780b2079',
  'symfony/yaml' => 'v5.2.14@ffe9c92e1a6c77c3ad5fc3a2ac16f0b8549dae10',
  'symfonycasts/reset-password-bundle' => 'v1.14.1@d906b72cff9a0683075041776a9c5e874df1918b',
  'twig/extra-bundle' => 'v3.7.0@802cc2dd46ec88285d6c7fa85c26ab7f2cd5bc49',
  'twig/twig' => 'v3.8.0@9d15f0ac07f44dc4217883ec6ae02fd555c6f71d',
  'webmozart/assert' => '1.11.0@11cb2199493b2f8a3b53e7f19068fc6aac760991',
  'doctrine/data-fixtures' => '1.7.0@bbcb74f2ac6dbe81a14b3c3687d7623490a0448f',
  'doctrine/doctrine-fixtures-bundle' => '3.4.5@5988484f79362cd7d06564bd11be7ce622e08c87',
  'nikic/php-parser' => 'v4.18.0@1bcbb2179f97633e98bbbc87044ee2611c7d7999',
  'symfony/browser-kit' => 'v5.2.12@ed7ebe262cef150742f5b61d48a94d37513c5758',
  'symfony/css-selector' => 'v5.2.12@7fb120adc7f600a59027775b224c13a33530dd90',
  'symfony/debug-bundle' => 'v5.2.12@2cb76e25ca75afb0d52c1ba83d77cd4190ed5552',
  'symfony/dom-crawler' => 'v5.2.12@c983279c00f723eef8da2a4b1522296c82dc75da',
  'symfony/maker-bundle' => 'v1.39.1@30c8ac13511f6df7bc9ac088f31d7a48ce6433c6',
  'symfony/phpunit-bridge' => 'v5.4.34@b3f772189bfc52e870233a040e888fc3b64c2a22',
  'symfony/web-profiler-bundle' => 'v5.2.13@380038080e46eb92b3a392de646fd32b632f1c77',
  'symfony/polyfill-ctype' => '*@c57efe9d38f0ddf11dac254a950425487a18864a',
  'symfony/polyfill-iconv' => '*@c57efe9d38f0ddf11dac254a950425487a18864a',
  'symfony/polyfill-php72' => '*@c57efe9d38f0ddf11dac254a950425487a18864a',
  '__root__' => 'dev-master@c57efe9d38f0ddf11dac254a950425487a18864a',
);

    private function __construct()
    {
    }

    /**
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function rootPackageName() : string
    {
        if (!class_exists(InstalledVersions::class, false) || !InstalledVersions::getRawData()) {
            return self::ROOT_PACKAGE_NAME;
        }

        return InstalledVersions::getRootPackage()['name'];
    }

    /**
     * @throws OutOfBoundsException If a version cannot be located.
     *
     * @psalm-param key-of<self::VERSIONS> $packageName
     * @psalm-pure
     *
     * @psalm-suppress ImpureMethodCall we know that {@see InstalledVersions} interaction does not
     *                                  cause any side effects here.
     */
    public static function getVersion(string $packageName): string
    {
        if (class_exists(InstalledVersions::class, false) && InstalledVersions::getRawData()) {
            return InstalledVersions::getPrettyVersion($packageName)
                . '@' . InstalledVersions::getReference($packageName);
        }

        if (isset(self::VERSIONS[$packageName])) {
            return self::VERSIONS[$packageName];
        }

        throw new OutOfBoundsException(
            'Required package "' . $packageName . '" is not installed: check your ./vendor/composer/installed.json and/or ./composer.lock files'
        );
    }
}
