<?php

namespace ContainerMbjIALu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JhEs3x9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JhEs3x9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JhEs3x9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'statutAdmin' => ['privates', 'App\\Repository\\StatusRepository', 'getStatusRepositoryService', true],
        ], [
            'statutAdmin' => 'App\\Repository\\StatusRepository',
        ]);
    }
}
