<?php

namespace ContainerMbjIALu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4Z28tv_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4Z28tv.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4Z28tv.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'taskModify' => ['privates', '.errored..service_locator.4Z28tv..App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.4Z28tv.": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'taskModify' => 'App\\Entity\\Task',
        ]);
    }
}
