<?php

namespace ContainerMbjIALu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRendezvousService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.531CKDe.App\Entity\Rendezvous' shared service.
     *
     * @return \App\Entity\Rendezvous
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.531CKDe": it references class "App\\Entity\\Rendezvous" but no such service exists.');
    }
}
