<?php

namespace ContainerMbjIALu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.zJXR4xe.App\Entity\Status' shared service.
     *
     * @return \App\Entity\Status
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.zJXR4xe": it references class "App\\Entity\\Status" but no such service exists.');
    }
}
