<?php

namespace ContainerMbjIALu;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTask23Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hcm3R5x.App\Entity\Task2' shared service.
     *
     * @return \App\Entity\Task2
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.hcm3R5x": it references class "App\\Entity\\Task2" but no such service exists.');
    }
}
