<?php

namespace ContainerXZylwL3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_TwNkgvVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.twNkgvV' shared service.
     *
     * @return \App\Controller\Front\SessionInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\SessionInterface". Did you forget to add a use statement?');
    }
}
