<?php

namespace ContainerXZylwL3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ATDFlVAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aTDFlVA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aTDFlVA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'quoteAdmin' => ['privates', 'App\\Repository\\QuoteRepository', 'getQuoteRepositoryService', true],
            'rendezvousAdmin' => ['privates', 'App\\Repository\\RendezvousRepository', 'getRendezvousRepositoryService', true],
            'tacheAdmin' => ['privates', 'App\\Repository\\TacheRepository', 'getTacheRepositoryService', true],
        ], [
            'quoteAdmin' => 'App\\Repository\\QuoteRepository',
            'rendezvousAdmin' => 'App\\Repository\\RendezvousRepository',
            'tacheAdmin' => 'App\\Repository\\TacheRepository',
        ]);
    }
}
