<?php

namespace ContainerXZylwL3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRendezvous2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._kWW_ZV.App\Entity\Rendezvous' shared service.
     *
     * @return \App\Entity\Rendezvous
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._kWW_ZV": it references class "App\\Entity\\Rendezvous" but no such service exists.');
    }
}
