<?php

namespace ContainerVfG4QMO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZJXR4xeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.zJXR4xe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.zJXR4xe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'statutDelete' => ['privates', '.errored..service_locator.zJXR4xe.App\\Entity\\Status', NULL, 'Cannot autowire service ".service_locator.zJXR4xe": it references class "App\\Entity\\Status" but no such service exists.'],
        ], [
            'statutDelete' => 'App\\Entity\\Status',
        ]);
    }
}
