<?php

namespace ContainerVfG4QMO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_EoB9RAfService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.eoB9RAf' shared service.
     *
     * @return \App\Controller\Front\TranslatorInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $translator argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\TranslatorInterface". Did you forget to add a use statement?');
    }
}
