<?php

namespace ContainerVfG4QMO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ht3vdiHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Ht3vdiH' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Ht3vdiH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'quoteDelete' => ['privates', '.errored..service_locator.Ht3vdiH.App\\Entity\\Quote', NULL, 'Cannot autowire service ".service_locator.Ht3vdiH": it references class "App\\Entity\\Quote" but no such service exists.'],
        ], [
            'quoteDelete' => 'App\\Entity\\Quote',
        ]);
    }
}
