<?php

namespace ContainerVfG4QMO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hcm3R5xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hcm3R5x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hcm3R5x'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'task2' => ['privates', '.errored..service_locator.hcm3R5x.App\\Entity\\Task2', NULL, 'Cannot autowire service ".service_locator.hcm3R5x": it references class "App\\Entity\\Task2" but no such service exists.'],
        ], [
            'task2' => 'App\\Entity\\Task2',
        ]);
    }
}
