<?php

namespace ContainerVfG4QMO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getForm_RegistryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'form.registry' shared service.
     *
     * @return \Symfony\Component\Form\FormRegistry
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormRegistry.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormExtensionInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DependencyInjection'.\DIRECTORY_SEPARATOR.'DependencyInjectionExtension.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactoryInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'Extension'.\DIRECTORY_SEPARATOR.'DataCollector'.\DIRECTORY_SEPARATOR.'Proxy'.\DIRECTORY_SEPARATOR.'ResolvedTypeFactoryDataCollectorProxy.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'ResolvedFormTypeFactory.php';

        return $container->privates['form.registry'] = new \Symfony\Component\Form\FormRegistry([0 => new \Symfony\Component\Form\Extension\DependencyInjection\DependencyInjectionExtension(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Form\\Back\\AdminCustomerAddType' => ['privates', 'App\\Form\\Back\\AdminCustomerAddType', 'getAdminCustomerAddTypeService', true],
            'App\\Form\\Back\\AdminCustomerModifyType' => ['privates', 'App\\Form\\Back\\AdminCustomerModifyType', 'getAdminCustomerModifyTypeService', true],
            'App\\Form\\Back\\AdminStatusAddType' => ['privates', 'App\\Form\\Back\\AdminStatusAddType', 'getAdminStatusAddTypeService', true],
            'App\\Form\\Back\\AdminTask2AddType' => ['privates', 'App\\Form\\Back\\AdminTask2AddType', 'getAdminTask2AddTypeService', true],
            'App\\Form\\Back\\AdminTaskAddType' => ['privates', 'App\\Form\\Back\\AdminTaskAddType', 'getAdminTaskAddTypeService', true],
            'App\\Form\\Back\\AdminTaskAppointmentAddType' => ['privates', 'App\\Form\\Back\\AdminTaskAppointmentAddType', 'getAdminTaskAppointmentAddTypeService', true],
            'App\\Form\\Back\\AdminTaskAppointmentModifyType' => ['privates', 'App\\Form\\Back\\AdminTaskAppointmentModifyType', 'getAdminTaskAppointmentModifyTypeService', true],
            'App\\Form\\Back\\AdminTaskModifyType' => ['privates', 'App\\Form\\Back\\AdminTaskModifyType', 'getAdminTaskModifyTypeService', true],
            'App\\Form\\Back\\AdminTaskQuoteAddType' => ['privates', 'App\\Form\\Back\\AdminTaskQuoteAddType', 'getAdminTaskQuoteAddTypeService', true],
            'App\\Form\\Back\\AdminUserAddType' => ['privates', 'App\\Form\\Back\\AdminUserAddType', 'getAdminUserAddTypeService', true],
            'App\\Form\\Back\\AdminUserModifyType' => ['privates', 'App\\Form\\Back\\AdminUserModifyType', 'getAdminUserModifyTypeService', true],
            'App\\Form\\ChangeCoordsType' => ['privates', 'App\\Form\\ChangeCoordsType', 'getChangeCoordsTypeService', true],
            'App\\Form\\ChangePasswordFormType' => ['privates', 'App\\Form\\ChangePasswordFormType', 'getChangePasswordFormTypeService', true],
            'App\\Form\\ChangePasswordType' => ['privates', 'App\\Form\\ChangePasswordType', 'getChangePasswordTypeService', true],
            'App\\Form\\RegisterType' => ['privates', 'App\\Form\\RegisterType', 'getRegisterTypeService', true],
            'App\\Form\\ResetPasswordRequestFormType' => ['privates', 'App\\Form\\ResetPasswordRequestFormType', 'getResetPasswordRequestFormTypeService', true],
            'App\\Form\\ShowHidePasswordType' => ['privates', 'App\\Form\\ShowHidePasswordType', 'getShowHidePasswordTypeService', true],
            'App\\Form\\UserMultipleType' => ['privates', 'App\\Form\\UserMultipleType', 'getUserMultipleTypeService', true],
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => ['privates', 'form.type.entity', 'getForm_Type_EntityService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => ['privates', 'form.type.choice', 'getForm_Type_ChoiceService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => ['privates', 'form.type.color', 'getForm_Type_ColorService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => ['services', '.container.private.form.type.file', 'get_Container_Private_Form_Type_FileService', true],
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => ['privates', 'form.type.form', 'getForm_Type_FormService', true],
        ], [
            'App\\Form\\Back\\AdminCustomerAddType' => '?',
            'App\\Form\\Back\\AdminCustomerModifyType' => '?',
            'App\\Form\\Back\\AdminStatusAddType' => '?',
            'App\\Form\\Back\\AdminTask2AddType' => '?',
            'App\\Form\\Back\\AdminTaskAddType' => '?',
            'App\\Form\\Back\\AdminTaskAppointmentAddType' => '?',
            'App\\Form\\Back\\AdminTaskAppointmentModifyType' => '?',
            'App\\Form\\Back\\AdminTaskModifyType' => '?',
            'App\\Form\\Back\\AdminTaskQuoteAddType' => '?',
            'App\\Form\\Back\\AdminUserAddType' => '?',
            'App\\Form\\Back\\AdminUserModifyType' => '?',
            'App\\Form\\ChangeCoordsType' => '?',
            'App\\Form\\ChangePasswordFormType' => '?',
            'App\\Form\\ChangePasswordType' => '?',
            'App\\Form\\RegisterType' => '?',
            'App\\Form\\ResetPasswordRequestFormType' => '?',
            'App\\Form\\ShowHidePasswordType' => '?',
            'App\\Form\\UserMultipleType' => '?',
            'Symfony\\Bridge\\Doctrine\\Form\\Type\\EntityType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ChoiceType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\ColorType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FileType' => '?',
            'Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => '?',
        ]), ['Symfony\\Component\\Form\\Extension\\Core\\Type\\FormType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.form.transformation_failure_handling'] ?? $container->load('getForm_TypeExtension_Form_TransformationFailureHandlingService'));
            yield 1 => ($container->privates['form.type_extension.form.http_foundation'] ?? $container->load('getForm_TypeExtension_Form_HttpFoundationService'));
            yield 2 => ($container->privates['form.type_extension.form.validator'] ?? $container->load('getForm_TypeExtension_Form_ValidatorService'));
            yield 3 => ($container->privates['form.type_extension.upload.validator'] ?? $container->load('getForm_TypeExtension_Upload_ValidatorService'));
            yield 4 => ($container->privates['form.type_extension.csrf'] ?? $container->load('getForm_TypeExtension_CsrfService'));
            yield 5 => ($container->privates['form.type_extension.form.data_collector'] ?? $container->load('getForm_TypeExtension_Form_DataCollectorService'));
        }, 6), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\RepeatedType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.repeated.validator'] ?? ($container->privates['form.type_extension.repeated.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\RepeatedTypeValidatorExtension()));
        }, 1), 'Symfony\\Component\\Form\\Extension\\Core\\Type\\SubmitType' => new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_extension.submit.validator'] ?? ($container->privates['form.type_extension.submit.validator'] = new \Symfony\Component\Form\Extension\Validator\Type\SubmitTypeValidatorExtension()));
        }, 1)], new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['form.type_guesser.validator'] ?? $container->load('getForm_TypeGuesser_ValidatorService'));
            yield 1 => ($container->privates['form.type_guesser.doctrine'] ?? $container->load('getForm_TypeGuesser_DoctrineService'));
        }, 2))], new \Symfony\Component\Form\Extension\DataCollector\Proxy\ResolvedTypeFactoryDataCollectorProxy(new \Symfony\Component\Form\ResolvedFormTypeFactory(), ($container->privates['data_collector.form'] ?? $container->getDataCollector_FormService())));
    }
}
