<?php

namespace ContainerVfG4QMO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuoteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.9CpGt2y.App\Entity\Quote' shared service.
     *
     * @return \App\Entity\Quote
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.9CpGt2y": it references class "App\\Entity\\Quote" but no such service exists.');
    }
}
