roles:
    ROLE_ADMIN: { label: Administrateur, show_p2_button: false, show_task_p1_cw_to_p1_nw_button: false, show_task_p1_modify_button: false, show_task_p1_delete_button: false }
    ROLE_STUDENT: { label: Stagiaire, show_task_p2_button: false }
