<<<<<<< ours
index:
    path: /
    controller: App\Controller\SecurityController::login
=======
controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
>>>>>>> theirs
