<?php

namespace ContainerB4xlWxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EKS65mzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EKS65mz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EKS65mz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'tacheModify' => ['privates', '.errored..service_locator.EKS65mz.App\\Entity\\Tache', NULL, 'Cannot autowire service ".service_locator.EKS65mz": it references class "App\\Entity\\Tache" but no such service exists.'],
        ], [
            'tacheModify' => 'App\\Entity\\Tache',
        ]);
    }
}
