<?php

namespace ContainerB4xlWxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9CpGt2yService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9CpGt2y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9CpGt2y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'quoteModify' => ['privates', '.errored..service_locator.9CpGt2y.App\\Entity\\Quote', NULL, 'Cannot autowire service ".service_locator.9CpGt2y": it references class "App\\Entity\\Quote" but no such service exists.'],
        ], [
            'quoteModify' => 'App\\Entity\\Quote',
        ]);
    }
}
