<?php

namespace ContainerB4xlWxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KWWZVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._kWW_ZV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._kWW_ZV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'appointmentModify' => ['privates', '.errored..service_locator._kWW_ZV.App\\Entity\\Rendezvous', NULL, 'Cannot autowire service ".service_locator._kWW_ZV": it references class "App\\Entity\\Rendezvous" but no such service exists.'],
        ], [
            'appointmentModify' => 'App\\Entity\\Rendezvous',
        ]);
    }
}
