<?php

namespace ContainerB4xlWxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DlV5Fm5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dlV5Fm5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dlV5Fm5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'task2Modify' => ['privates', '.errored..service_locator.dlV5Fm5.App\\Entity\\Task2', NULL, 'Cannot autowire service ".service_locator.dlV5Fm5": it references class "App\\Entity\\Task2" but no such service exists.'],
        ], [
            'task2Modify' => 'App\\Entity\\Task2',
        ]);
    }
}
