<?php

namespace ContainerB4xlWxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_3TggW7hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.3TggW7h' shared service.
     *
     * @return \App\Controller\Front\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\Request". Did you forget to add a use statement?');
    }
}
