<?php

namespace ContainerB4xlWxp;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuote2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.Ht3vdiH.App\Entity\Quote' shared service.
     *
     * @return \App\Entity\Quote
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.Ht3vdiH": it references class "App\\Entity\\Quote" but no such service exists.');
    }
}
