<?php

namespace ContainerXVIV7qr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_PVbX1FQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.PVbX1FQ' shared service.
     *
     * @return \App\Controller\Front\TokenStorageInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $tokenStorage argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\TokenStorageInterface". Did you forget to add a use statement?');
    }
}
