<?php

namespace ContainerXVIV7qr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_531CKDeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.531CKDe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.531CKDe'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'rendezvousDelete' => ['privates', '.errored..service_locator.531CKDe.App\\Entity\\Rendezvous', NULL, 'Cannot autowire service ".service_locator.531CKDe": it references class "App\\Entity\\Rendezvous" but no such service exists.'],
        ], [
            'rendezvousDelete' => 'App\\Entity\\Rendezvous',
        ]);
    }
}
