<?php

namespace ContainerXVIV7qr;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GHm1lEFService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gHm1lEF' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gHm1lEF'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'em' => ['privates', '.errored.7.0VfmM', NULL, 'Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $em argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\EntityManagerInterface". Did you forget to add a use statement?'],
            'errorCollector' => ['privates', '.errored.4W85RKh', NULL, 'Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $errorCollector argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\FormErrorCollector". Did you forget to add a use statement?'],
            'request' => ['privates', '.errored.3TggW7h', NULL, 'Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\Request". Did you forget to add a use statement?'],
            'session' => ['privates', '.errored.twNkgvV', NULL, 'Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $session argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\SessionInterface". Did you forget to add a use statement?'],
            'tokenStorage' => ['privates', '.errored.PVbX1FQ', NULL, 'Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $tokenStorage argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\TokenStorageInterface". Did you forget to add a use statement?'],
            'translator' => ['privates', '.errored.eoB9RAf', NULL, 'Cannot determine controller argument for "App\\Controller\\Front\\DeleteAccountController::deleteUserAction()": the $translator argument is type-hinted with the non-existent class or interface: "App\\Controller\\Front\\TranslatorInterface". Did you forget to add a use statement?'],
        ], [
            'em' => '?',
            'errorCollector' => '?',
            'request' => '?',
            'session' => '?',
            'tokenStorage' => '?',
            'translator' => '?',
        ]);
    }
}
